on: push
name: Run tests
jobs:
  spec_tests:
    name: Spec tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}
        # Don't need an extension when using phpdbg.
        coverage: none
    - name: Install Dependencies
      run: |
        composer install --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Spec tests
      run: |
        phpdbg -qrr ./vendor/bin/phpspec run
    - name: Upload coverage report to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -c -F spec -n Spec

  build:
    name: Docker build and push
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    needs: spec_tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      if: github.ref == 'refs/heads/master'
      uses: anothrNick/github-tag-action@master
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        # Currently ghcr.io only supports a personal access token, so
        # this is one from reload-deploy.
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        tags: |
          ghcr.io/reload/bug-yield:latest
          ghcr.io/reload/bug-yield:${{ steps.version.outputs.new_tag }}
        push: true
