on: push
name: Run tests
jobs:
  spec_tests:
    name: Spec tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-version }}
        # Don't need an extension when using phpdbg.
        coverage: none
    - name: Install Dependencies
      run: |
        composer install --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Spec tests
      run: |
        phpdbg -qrr ./vendor/bin/phpspec run
    - name: Upload coverage report to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -c -F spec -n Spec
